stages:
  prepare_hepg2_els:
    cmd: bash src/get_hepg2_ELS.sh
    deps:
    - data/raw/hepg2_cCREs.bed
    - src/get_hepg2_ELS.sh
    outs:
    - data/processed/hepg2_ELS.bed
    - data/processed/hepg2_ELS.trimmed.bed
  build_negatives:
    cmd: Rscript --vanilla src/build_negs.R
    deps:
    - data/processed/hepg2_ELS.trimmed.bed
    - src/build_negs.R
    outs:
    - data/processed/hepg2_ELS.trimmed.fa
    - data/processed/negatives/neg1x_hepg2_ELS.trimmed.bed
    - data/processed/negatives/neg1x_hepg2_ELS.trimmed.fa
