stages:
  prepare_hepg2_els:
    cmd: bash src/get_hepg2_ELS.sh
    deps:
    - data/raw/hepg2_cCREs.bed
    - src/get_hepg2_ELS.sh
    outs:
    - data/processed/evn/hepg2_ELS.bed
    - data/processed/evn/hepg2_ELS.trimmed.bed
  make_folds:
    cmd: bash src/make_folds.sh
    deps:
    - data/processed/evn/hepg2_ELS.trimmed.bed
    - src/make_folds.sh
    outs:
    - data/processed/evn/folds/fold1/fold1.bed
    - data/processed/evn/folds/fold2/fold2.bed
    - data/processed/evn/folds/fold3/fold3.bed
    - data/processed/evn/folds/fold4/fold4.bed
    - data/processed/evn/folds/fold5/fold5.bed
  build_negatives:
    cmd: Rscript --vanilla src/build_negs.R <fold_nr>
    deps:
    - src/build_negs.R
    - data/processed/evn/folds/fold1/fold1.bed
    - data/processed/evn/folds/fold2/fold2.bed
    - data/processed/evn/folds/fold3/fold3.bed
    - data/processed/evn/folds/fold4/fold4.bed
    - data/processed/evn/folds/fold5/fold5.bed
    outs:
    - data/processed/evn/folds/fold1/fold1.fa
    - data/processed/evn/folds/fold1/neg1x_fold1.bed
    - data/processed/evn/folds/fold1/neg1x_fold1.fa
    - data/processed/evn/folds/fold2/fold2.fa
    - data/processed/evn/folds/fold2/neg1x_fold2.bed
    - data/processed/evn/folds/fold2/neg1x_fold2.fa
    - data/processed/evn/folds/fold3/fold3.fa
    - data/processed/evn/folds/fold3/neg1x_fold3.bed
    - data/processed/evn/folds/fold3/neg1x_fold3.fa
    - data/processed/evn/folds/fold4/fold4.fa
    - data/processed/evn/folds/fold4/neg1x_fold4.bed
    - data/processed/evn/folds/fold4/neg1x_fold4.fa
    - data/processed/evn/folds/fold5/fold5.fa
    - data/processed/evn/folds/fold5/neg1x_fold5.bed
    - data/processed/evn/folds/fold5/neg1x_fold5.fa
  make_outer_files:
    cmd: for i in 1 2 3 4 5; do bash src/make_outer_files.sh "$i"; done
    deps:
    - data/processed/evn/folds/fold1/fold1.fa
    - data/processed/evn/folds/fold1/neg1x_fold1.fa
    - data/processed/evn/folds/fold2/fold2.fa
    - data/processed/evn/folds/fold2/neg1x_fold2.fa
    - data/processed/evn/folds/fold3/fold3.fa
    - data/processed/evn/folds/fold3/neg1x_fold3.fa
    - data/processed/evn/folds/fold4/fold4.fa
    - data/processed/evn/folds/fold4/neg1x_fold4.fa
    - data/processed/evn/folds/fold5/fold5.fa
    - data/processed/evn/folds/fold5/neg1x_fold5.fa
    - src/make_outer_files.sh
    outs:
    - data/processed/evn/ls-gkm/training/outer1/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer1/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer2/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer2/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer3/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer3/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer4/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer4/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer5/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer5/train_pos.fa
  train_ls_gkm:
    cmd: bash ../lsgkm/bin/gkmtrain -T 4 -m 16000 '<pos_fa>' '<neg_fa>' 
      'output_prefix'
    deps:
    - ../lsgkm/bin/gkmtrain
    - data/processed/evn/ls-gkm/training/outer1/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer1/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer2/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer2/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer3/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer3/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer4/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer4/train_pos.fa
    - data/processed/evn/ls-gkm/training/outer5/train_neg.fa
    - data/processed/evn/ls-gkm/training/outer5/train_pos.fa
    outs:
    - models/evn/ls-gkm/outer1.model.txt
    - models/evn/ls-gkm/outer2.model.txt
    - models/evn/ls-gkm/outer3.model.txt
    - models/evn/ls-gkm/outer4.model.txt
    - models/evn/ls-gkm/outer5.model.txt
  test_ls_gkm:
    cmd: bash ../lsgkm/bin/gkmpredict -T 4 '<fasta>' '<model>' 'output'
    deps:
    - ../lsgkm/bin/gkmpredict
    - models/evn/ls-gkm/outer1.model.txt
    - models/evn/ls-gkm/outer2.model.txt
    - models/evn/ls-gkm/outer3.model.txt
    - models/evn/ls-gkm/outer4.model.txt
    - models/evn/ls-gkm/outer5.model.txt
    outs:
    - predictions/evn/ls-gkm/outer1/pos_scores.txt
    - predictions/evn/ls-gkm/outer1/neg_scores.txt
    - predictions/evn/ls-gkm/outer2/pos_scores.txt
    - predictions/evn/ls-gkm/outer2/neg_scores.txt
    - predictions/evn/ls-gkm/outer3/pos_scores.txt
    - predictions/evn/ls-gkm/outer3/neg_scores.txt
    - predictions/evn/ls-gkm/outer4/pos_scores.txt
    - predictions/evn/ls-gkm/outer4/neg_scores.txt
    - predictions/evn/ls-gkm/outer5/pos_scores.txt
    - predictions/evn/ls-gkm/outer5/neg_scores.txt
  merge_pos_negs:
    cmd: for i in 1 2 3 4 5; do Rscript src/prepare_lsgkm_scores.R 
      predictions/evn/ls-gkm/outer"$i"; done
    deps:
    - predictions/evn/ls-gkm/outer1/neg_scores.txt
    - predictions/evn/ls-gkm/outer1/pos_scores.txt
    - predictions/evn/ls-gkm/outer2/neg_scores.txt
    - predictions/evn/ls-gkm/outer2/pos_scores.txt
    - predictions/evn/ls-gkm/outer3/neg_scores.txt
    - predictions/evn/ls-gkm/outer3/pos_scores.txt
    - predictions/evn/ls-gkm/outer4/neg_scores.txt
    - predictions/evn/ls-gkm/outer4/pos_scores.txt
    - predictions/evn/ls-gkm/outer5/neg_scores.txt
    - predictions/evn/ls-gkm/outer5/pos_scores.txt
    - src/prepare_lsgkm_scores.R
    outs:
    - results/evn/ls-gkm/outer1.tsv
    - results/evn/ls-gkm/outer2.tsv
    - results/evn/ls-gkm/outer3.tsv
    - results/evn/ls-gkm/outer4.tsv
    - results/evn/ls-gkm/outer5.tsv
  merge_outers:
    cmd: |
      {
        head -n 1 results/evn/ls-gkm/outer1.tsv
        for FOLD in 1 2 3 4 5; do
          tail -n +2 "results/evn/ls-gkm/outer$FOLD.tsv"
        done
      } > results/evn/ls-gkm/all_outers.tsv    
    deps:
    - results/evn/ls-gkm/outer1.tsv
    - results/evn/ls-gkm/outer2.tsv
    - results/evn/ls-gkm/outer3.tsv
    - results/evn/ls-gkm/outer4.tsv
    - results/evn/ls-gkm/outer5.tsv
    outs:
    - results/evn/ls-gkm/all_outer.tsv
